version: '3.8'

services:
  phpnuxbill:
    build: .
    container_name: phpnuxbill
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html
    restart: always

  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: phpnuxbill
      MYSQL_USER: nuxuser
      MYSQL_PASSWORD: nuxpass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

